[package]
name = "ml-project"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
linfa = "0.8.1"
linfa-datasets = "0.8.1"
linfa-logistic = "0.8.1"
linfa-preprocessing = "0.8.1"
ndarray = "0.16.1"
